a=imread('cameraman.tif');
subplot(2,3,1),imshow(a),title('original Image');
se=strel('line',7,7);
eroded_Img=imerode(a,se);
dilated_Img=imdilate(a,se);
opened_Img=imopen(a,se);
closed_Img=imclose(a,se);
subplot(2,3,2),imshow(eroded_Img),title('Eroded Image');
subplot(2,3,3),imshow(dilated_Img),title('Dilated Image');
subplot(2,3,4),imshow(opened_Img),title('Opened Image');
subplot(2,3,5),imshow(closed_Img),title('Closed Image');